/*
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.l2jfree.loginserver.beans;

// Generated 16 dec. 2006 13:48:45 by Hibernate Tools 3.2.0.beta8

/**
 * Gameservers generated by hbm2java
 */
public class Gameservers implements java.io.Serializable
{

	// Fields    

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 2293307012167588040L;
	private String				serverName;
	private int					serverId;
	private String				hexid;
	private String				host;

	// Constructors

	/** default constructor */
	public Gameservers()
	{
	}

	/** full constructor */
	public Gameservers(int _serverId, String _hexid, String _host)
	{
		this.serverId = _serverId;
		this.hexid = _hexid;
		this.host = _host;
	}

	// Property accessors
	public int getServerId()
	{
		return this.serverId;
	}

	public void setServerId(int _serverId)
	{
		this.serverId = _serverId;
	}

	public String getHexid()
	{
		return this.hexid;
	}

	public void setHexid(String _hexid)
	{
		this.hexid = _hexid;
	}

	public String getHost()
	{
		return this.host;
	}

	public void setHost(String _host)
	{
		this.host = _host;
	}

	public String getServerName()
	{
		return this.serverName;
	}

	public void setServerName(String _serverName)
	{
		this.serverName = _serverName;
	}

}
