package net.sf.l2j.gameserver.beans;

// Generated 19 févr. 2007 22:07:55 by Hibernate Tools 3.2.0.beta8

/**
 * ForumsId generated by hbm2java
 */
public class ForumsId implements java.io.Serializable
{

    // Fields    

    /**
     * Comment for <code>serialVersionUID</code>
     */
    private static final long serialVersionUID = 8277515635874941734L;
    private int forumId;
    private String forumName;
    private int forumParent;
    private int forumPost;
    private int forumType;
    private int forumPerm;
    private int forumOwnerId;

    // Constructors

    /** default constructor */
    public ForumsId()
    {
    }

    /** full constructor */
    public ForumsId(int _forumId, String _forumName, int _forumParent, int _forumPost, int _forumType,
                    int _forumPerm, int _forumOwnerId)
    {
        this.forumId = _forumId;
        this.forumName = _forumName;
        this.forumParent = _forumParent;
        this.forumPost = _forumPost;
        this.forumType = _forumType;
        this.forumPerm = _forumPerm;
        this.forumOwnerId = _forumOwnerId;
    }

    // Property accessors
    public int getForumId()
    {
        return this.forumId;
    }

    public void setForumId(int _forumId)
    {
        this.forumId = _forumId;
    }

    public String getForumName()
    {
        return this.forumName;
    }

    public void setForumName(String _forumName)
    {
        this.forumName = _forumName;
    }

    public int getForumParent()
    {
        return this.forumParent;
    }

    public void setForumParent(int _forumParent)
    {
        this.forumParent = _forumParent;
    }

    public int getForumPost()
    {
        return this.forumPost;
    }

    public void setForumPost(int _forumPost)
    {
        this.forumPost = _forumPost;
    }

    public int getForumType()
    {
        return this.forumType;
    }

    public void setForumType(int _forumType)
    {
        this.forumType = _forumType;
    }

    public int getForumPerm()
    {
        return this.forumPerm;
    }

    public void setForumPerm(int _forumPerm)
    {
        this.forumPerm = _forumPerm;
    }

    public int getForumOwnerId()
    {
        return this.forumOwnerId;
    }

    public void setForumOwnerId(int _forumOwnerId)
    {
        this.forumOwnerId = _forumOwnerId;
    }

    public boolean equals(Object other)
    {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof ForumsId)) return false;
        ForumsId castOther = (ForumsId) other;

        return (this.getForumId() == castOther.getForumId())
            && ((this.getForumName() == castOther.getForumName()) || (this.getForumName() != null
                && castOther.getForumName() != null && this.getForumName().equals(
                                                                                  castOther.getForumName())))
            && (this.getForumParent() == castOther.getForumParent())
            && (this.getForumPost() == castOther.getForumPost())
            && (this.getForumType() == castOther.getForumType())
            && (this.getForumPerm() == castOther.getForumPerm())
            && (this.getForumOwnerId() == castOther.getForumOwnerId());
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + this.getForumId();
        result = 37 * result + (getForumName() == null ? 0 : this.getForumName().hashCode());
        result = 37 * result + this.getForumParent();
        result = 37 * result + this.getForumPost();
        result = 37 * result + this.getForumType();
        result = 37 * result + this.getForumPerm();
        result = 37 * result + this.getForumOwnerId();
        return result;
    }

}
