package net.sf.l2j.gameserver.beans;

// Generated 19 févr. 2007 22:07:55 by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * Forums generated by hbm2java
 */
public class Forums implements java.io.Serializable
{

    // Fields    

    /**
     * Comment for <code>serialVersionUID</code>
     */
    private static final long serialVersionUID = -8074717730201663809L;
    private ForumsId id;
    private Set<Posts> postses = new HashSet<Posts>(0);
    private Set<Topic> topics = new HashSet<Topic>(0);

    // Constructors

    /** default constructor */
    public Forums()
    {
    }

    /** minimal constructor */
    public Forums(ForumsId _id)
    {
        this.id = _id;
    }

    /** full constructor */
    public Forums(ForumsId _id, Set<Posts> _postses, Set<Topic> _topics)
    {
        this.id = _id;
        this.postses = _postses;
        this.topics = _topics;
    }

    // Property accessors
    public ForumsId getId()
    {
        return this.id;
    }

    public void setId(ForumsId _id)
    {
        this.id = _id;
    }

    public Set<Posts> getPostses()
    {
        return this.postses;
    }

    public void setPostses(Set<Posts> _postses)
    {
        this.postses = _postses;
    }

    public Set<Topic> getTopics()
    {
        return this.topics;
    }

    public void setTopics(Set<Topic> _topics)
    {
        this.topics = _topics;
    }

}
