package net.sf.l2j.gameserver.beans;

import java.util.HashSet;
import java.util.Set;

// Generated 19 févr. 2007 22:07:55 by Hibernate Tools 3.2.0.beta8

/**
 * Topic generated by hbm2java
 */
public class Topic implements java.io.Serializable
{

    // Fields    

    /**
     * Comment for <code>serialVersionUID</code>
     */
    private static final long serialVersionUID = 1673919324213673955L;
    private TopicId id;
    private Forums forums;
    private Set<Posts> postses = new HashSet<Posts>(0);
    

    // Constructors

    /** default constructor */
    public Topic()
    {
    }

    /** full constructor */
    public Topic(TopicId _id, Forums _forums)
    {
        this.id = _id;
        this.forums = _forums;
    }

    // Property accessors
    public TopicId getId()
    {
        return this.id;
    }

    public void setId(TopicId _id)
    {
        this.id = _id;
    }

    public Forums getForums()
    {
        return this.forums;
    }

    public void setForums(Forums _forums)
    {
        this.forums =_forums;
    }
    public Set<Posts> getPostses()
    {
        return this.postses;
    }

    public void setPostses(Set<Posts> _postses)
    {
        this.postses = _postses;
    }    

}
