package net.sf.l2j.gameserver.beans;

// Generated 19 févr. 2007 22:07:55 by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;

/**
 * TopicId generated by hbm2java
 */
public class TopicId implements java.io.Serializable
{

    // Fields    

    /**
     * Comment for <code>serialVersionUID</code>
     */
    private static final long serialVersionUID = 376498683387654718L;
    private int topicId;
    private int topicForumId;
    private String topicName;
    private BigDecimal topicDate;
    private String topicOwnername;
    private int topicOwnerid;
    private int topicType;
    private int topicReply;

    // Constructors

    /** default constructor */
    public TopicId()
    {
    }

    /** full constructor */
    public TopicId(int _topicId, int _topicForumId, String _topicName, BigDecimal _topicDate,
                   String _topicOwnername, int _topicOwnerid, int _topicType, int _topicReply)
    {
        this.topicId = _topicId;
        this.topicForumId = _topicForumId;
        this.topicName = _topicName;
        this.topicDate = _topicDate;
        this.topicOwnername = _topicOwnername;
        this.topicOwnerid = _topicOwnerid;
        this.topicType = _topicType;
        this.topicReply = _topicReply;
    }

    // Property accessors
    public int getTopicId()
    {
        return this.topicId;
    }

    public void setTopicId(int _topicId)
    {
        this.topicId = _topicId;
    }

    public int getTopicForumId()
    {
        return this.topicForumId;
    }

    public void setTopicForumId(int _topicForumId)
    {
        this.topicForumId = _topicForumId;
    }

    public String getTopicName()
    {
        return this.topicName;
    }

    public void setTopicName(String _topicName)
    {
        this.topicName = _topicName;
    }

    public BigDecimal getTopicDate()
    {
        return this.topicDate;
    }

    public void setTopicDate(BigDecimal _topicDate)
    {
        this.topicDate = _topicDate;
    }

    public String getTopicOwnername()
    {
        return this.topicOwnername;
    }

    public void setTopicOwnername(String _topicOwnername)
    {
        this.topicOwnername = _topicOwnername;
    }

    public int getTopicOwnerid()
    {
        return this.topicOwnerid;
    }

    public void setTopicOwnerid(int _topicOwnerid)
    {
        this.topicOwnerid = _topicOwnerid;
    }

    public int getTopicType()
    {
        return this.topicType;
    }

    public void setTopicType(int _topicType)
    {
        this.topicType = _topicType;
    }

    public int getTopicReply()
    {
        return this.topicReply;
    }

    public void setTopicReply(int _topicReply)
    {
        this.topicReply = _topicReply;
    }

    public boolean equals(Object other)
    {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof TopicId)) return false;
        TopicId castOther = (TopicId) other;

        return (this.getTopicId() == castOther.getTopicId())
            && (this.getTopicForumId() == castOther.getTopicForumId())
            && ((this.getTopicName() == castOther.getTopicName()) || (this.getTopicName() != null
                && castOther.getTopicName() != null && this.getTopicName().equals(
                                                                                  castOther.getTopicName())))
            && ((this.getTopicDate() == castOther.getTopicDate()) || (this.getTopicDate() != null
                && castOther.getTopicDate() != null && this.getTopicDate().equals(
                                                                                  castOther.getTopicDate())))
            && ((this.getTopicOwnername() == castOther.getTopicOwnername()) || (this.getTopicOwnername() != null
                && castOther.getTopicOwnername() != null && this.getTopicOwnername().equals(
                                                                                            castOther.getTopicOwnername())))
            && (this.getTopicOwnerid() == castOther.getTopicOwnerid())
            && (this.getTopicType() == castOther.getTopicType())
            && (this.getTopicReply() == castOther.getTopicReply());
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + this.getTopicId();
        result = 37 * result + this.getTopicForumId();
        result = 37 * result + (getTopicName() == null ? 0 : this.getTopicName().hashCode());
        result = 37 * result + (getTopicDate() == null ? 0 : this.getTopicDate().hashCode());
        result = 37 * result + (getTopicOwnername() == null ? 0 : this.getTopicOwnername().hashCode());
        result = 37 * result + this.getTopicOwnerid();
        result = 37 * result + this.getTopicType();
        result = 37 * result + this.getTopicReply();
        return result;
    }

}
