package net.sf.l2j.loginserver.beans;

// Generated 8 déc. 2006 15:26:57 by Hibernate Tools 3.2.0.beta8

/**
 * AccountData generated by hbm2java
 */
public class AccountData implements java.io.Serializable
{

    // Fields    

    private AccountDataId id;
    private String value;

    // Constructors

    /** default constructor */
    public AccountData()
    {
    }

    /** minimal constructor */
    public AccountData(AccountDataId id)
    {
        this.id = id;
    }

    /** full constructor */
    public AccountData(AccountDataId id, String value)
    {
        this.id = id;
        this.value = value;
    }

    // Property accessors
    public AccountDataId getId()
    {
        return this.id;
    }

    public void setId(AccountDataId id)
    {
        this.id = id;
    }

    public String getValue()
    {
        return this.value;
    }

    public void setValue(String value)
    {
        this.value = value;
    }

}
