package net.sf.l2j.loginserver.beans;

// Generated 7 déc. 2006 18:49:51 by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Accounts generated by hbm2java
 */
public class Accounts implements java.io.Serializable
{
    // Fields    

    private static final long serialVersionUID = 1L;
    private String login;
    private String password;
    private BigDecimal lastactive;
    private Integer accessLevel;
    private String lastIp;
    private String email;
    private Set<Characters> characterses = new HashSet<Characters>(0);
    private Set<AccountData> accountDatas = new HashSet<AccountData>(0);

    // Constructors

    /** default constructor */
    public Accounts()
    {
    }

    /** minimal constructor */
    public Accounts(String _login, String _email)
    {
        this.login = _login;
        this.email = _email;
    }

    /** full constructor */
    public Accounts(String _login, String _password, BigDecimal _lastactive, Integer _accessLevel,
                    String _lastIp, String _email, Set<Characters> _characterses)
    {
        this.login = _login;
        this.password = _password;
        this.lastactive = _lastactive;
        this.accessLevel = _accessLevel;
        this.lastIp = _lastIp;
        this.email =_email;
        this.characterses = _characterses;
    }

    // Property accessors
    public String getLogin()
    {
        return this.login;
    }

    public void setLogin(String _login)
    {
        this.login = _login;
    }

    public String getPassword()
    {
        return this.password;
    }

    public void setPassword(String _password)
    {
        this.password = _password;
    }

    public BigDecimal getLastactive()
    {
        return this.lastactive;
    }

    public void setLastactive(BigDecimal _lastactive)
    {
        this.lastactive = _lastactive;
    }

    public Integer getAccessLevel()
    {
        return this.accessLevel;
    }

    public void setAccessLevel(Integer _accessLevel)
    {
        this.accessLevel = _accessLevel;
    }

    public String getLastIp()
    {
        return this.lastIp;
    }

    public void setLastIp(String _lastIp)
    {
        this.lastIp = _lastIp;
    }

    public String getEmail()
    {
        return this.email;
    }

    public void setEmail(String _email)
    {
        this.email = _email;
    }

    public Set<Characters> getCharacterses()
    {
        return this.characterses;
    }

    public void setCharacterses(Set<Characters> _characterses)
    {
        this.characterses = _characterses;
    }

    public void setAccountDatas(Set<AccountData> _accountDatas)
    {
        this.accountDatas = _accountDatas;
    }
    public Set<AccountData> getAccountDatas()
    {
        return this.accountDatas;
    }

}
