package net.sf.l2j.loginserver.beans;

// Generated 11 déc. 2006 17:28:16 by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Accounts generated by hbm2java
 */
public class Accounts implements java.io.Serializable
{

    // Fields    

    private String login;
    private String password;
    private BigDecimal lastactive;
    private Integer accessLevel;
    private String lastIp;
    private String email;
    private Set<Characters> characterses = new HashSet<Characters>(0);
    private Set<AccountData> accountDatas = new HashSet<AccountData>(0);

    // Constructors

    /** default constructor */
    public Accounts()
    {
    }

    /** minimal constructor */
    public Accounts(String login)
    {
        this.login = login;
    }

    /** full constructor */
    public Accounts(String login, String password, BigDecimal lastactive, Integer accessLevel,
                    String lastIp, String email, Set<Characters> characterses,
                    Set<AccountData> accountDatas)
    {
        this.login = login;
        this.password = password;
        this.lastactive = lastactive;
        this.accessLevel = accessLevel;
        this.lastIp = lastIp;
        this.email = email;
        this.characterses = characterses;
        this.accountDatas = accountDatas;
    }

    // Property accessors
    public String getLogin()
    {
        return this.login;
    }

    public void setLogin(String login)
    {
        this.login = login;
    }

    public String getPassword()
    {
        return this.password;
    }

    public void setPassword(String password)
    {
        this.password = password;
    }

    public BigDecimal getLastactive()
    {
        return this.lastactive;
    }

    public void setLastactive(BigDecimal lastactive)
    {
        this.lastactive = lastactive;
    }

    public Integer getAccessLevel()
    {
        return this.accessLevel;
    }

    public void setAccessLevel(Integer accessLevel)
    {
        this.accessLevel = accessLevel;
    }

    public String getLastIp()
    {
        return this.lastIp;
    }

    public void setLastIp(String lastIp)
    {
        this.lastIp = lastIp;
    }

    public String getEmail()
    {
        return this.email;
    }

    public void setEmail(String email)
    {
        this.email = email;
    }

    public Set<Characters> getCharacterses()
    {
        return this.characterses;
    }

    public void setCharacterses(Set<Characters> characterses)
    {
        this.characterses = characterses;
    }

    public Set<AccountData> getAccountDatas()
    {
        return this.accountDatas;
    }

    public void setAccountDatas(Set<AccountData> accountDatas)
    {
        this.accountDatas = accountDatas;
    }

}
