package net.sf.l2j.loginserver.beans;

// Generated 11 déc. 2006 17:28:16 by Hibernate Tools 3.2.0.beta8

/**
 * BoxaccessId generated by hbm2java
 */
public class BoxaccessId implements java.io.Serializable
{

    // Fields    

    private Long spawn;
    private String charname;

    // Constructors

    /** default constructor */
    public BoxaccessId()
    {
    }

    /** full constructor */
    public BoxaccessId(Long spawn, String charname)
    {
        this.spawn = spawn;
        this.charname = charname;
    }

    // Property accessors
    public Long getSpawn()
    {
        return this.spawn;
    }

    public void setSpawn(Long spawn)
    {
        this.spawn = spawn;
    }

    public String getCharname()
    {
        return this.charname;
    }

    public void setCharname(String charname)
    {
        this.charname = charname;
    }

    public boolean equals(Object other)
    {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof BoxaccessId)) return false;
        BoxaccessId castOther = (BoxaccessId) other;

        return ((this.getSpawn() == castOther.getSpawn()) || (this.getSpawn() != null
            && castOther.getSpawn() != null && this.getSpawn().equals(castOther.getSpawn())))
            && ((this.getCharname() == castOther.getCharname()) || (this.getCharname() != null
                && castOther.getCharname() != null && this.getCharname().equals(castOther.getCharname())));
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + (getSpawn() == null ? 0 : this.getSpawn().hashCode());
        result = 37 * result + (getCharname() == null ? 0 : this.getCharname().hashCode());
        return result;
    }

}
