package net.sf.l2j.loginserver.beans;

// Generated 11 déc. 2006 17:28:16 by Hibernate Tools 3.2.0.beta8

/**
 * CharacterSkills generated by hbm2java
 */
public class CharacterSkills implements java.io.Serializable
{

    // Fields    

    private CharacterSkillsId id;
    private Characters characters;
    private String skillLevel;
    private String skillName;

    // Constructors

    /** default constructor */
    public CharacterSkills()
    {
    }

    /** minimal constructor */
    public CharacterSkills(CharacterSkillsId id, Characters characters)
    {
        this.id = id;
        this.characters = characters;
    }

    /** full constructor */
    public CharacterSkills(CharacterSkillsId id, Characters characters, String skillLevel,
                           String skillName)
    {
        this.id = id;
        this.characters = characters;
        this.skillLevel = skillLevel;
        this.skillName = skillName;
    }

    // Property accessors
    public CharacterSkillsId getId()
    {
        return this.id;
    }

    public void setId(CharacterSkillsId id)
    {
        this.id = id;
    }

    public Characters getCharacters()
    {
        return this.characters;
    }

    public void setCharacters(Characters characters)
    {
        this.characters = characters;
    }

    public String getSkillLevel()
    {
        return this.skillLevel;
    }

    public void setSkillLevel(String skillLevel)
    {
        this.skillLevel = skillLevel;
    }

    public String getSkillName()
    {
        return this.skillName;
    }

    public void setSkillName(String skillName)
    {
        this.skillName = skillName;
    }

}
