package net.sf.l2j.loginserver.beans;

// Generated 7 déc. 2006 18:49:51 by Hibernate Tools 3.2.0.beta8

/**
 * CharacterSkillsSaveId generated by hbm2java
 */
public class CharacterSkillsSaveId implements java.io.Serializable
{

    // Fields    

    private int charObjId;
    private int skillId;
    private int classIndex;

    // Constructors

    /** default constructor */
    public CharacterSkillsSaveId()
    {
    }

    /** full constructor */
    public CharacterSkillsSaveId(int charObjId, int skillId, int classIndex)
    {
        this.charObjId = charObjId;
        this.skillId = skillId;
        this.classIndex = classIndex;
    }

    // Property accessors
    public int getCharObjId()
    {
        return this.charObjId;
    }

    public void setCharObjId(int charObjId)
    {
        this.charObjId = charObjId;
    }

    public int getSkillId()
    {
        return this.skillId;
    }

    public void setSkillId(int skillId)
    {
        this.skillId = skillId;
    }

    public int getClassIndex()
    {
        return this.classIndex;
    }

    public void setClassIndex(int classIndex)
    {
        this.classIndex = classIndex;
    }

    public boolean equals(Object other)
    {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof CharacterSkillsSaveId)) return false;
        CharacterSkillsSaveId castOther = (CharacterSkillsSaveId) other;

        return (this.getCharObjId() == castOther.getCharObjId())
            && (this.getSkillId() == castOther.getSkillId())
            && (this.getClassIndex() == castOther.getClassIndex());
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + this.getCharObjId();
        result = 37 * result + this.getSkillId();
        result = 37 * result + this.getClassIndex();
        return result;
    }

}
