package net.sf.l2j.loginserver.beans;

// Generated 11 déc. 2006 17:28:16 by Hibernate Tools 3.2.0.beta8

/**
 * CharacterShortcutsId generated by hbm2java
 */
public class CharacterShortcutsId implements java.io.Serializable
{

    // Fields    

    private int charObjId;
    private short slot;
    private short page;
    private int classIndex;

    // Constructors

    /** default constructor */
    public CharacterShortcutsId()
    {
    }

    /** full constructor */
    public CharacterShortcutsId(int charObjId, short slot, short page, int classIndex)
    {
        this.charObjId = charObjId;
        this.slot = slot;
        this.page = page;
        this.classIndex = classIndex;
    }

    // Property accessors
    public int getCharObjId()
    {
        return this.charObjId;
    }

    public void setCharObjId(int charObjId)
    {
        this.charObjId = charObjId;
    }

    public short getSlot()
    {
        return this.slot;
    }

    public void setSlot(short slot)
    {
        this.slot = slot;
    }

    public short getPage()
    {
        return this.page;
    }

    public void setPage(short page)
    {
        this.page = page;
    }

    public int getClassIndex()
    {
        return this.classIndex;
    }

    public void setClassIndex(int classIndex)
    {
        this.classIndex = classIndex;
    }

    public boolean equals(Object other)
    {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof CharacterShortcutsId)) return false;
        CharacterShortcutsId castOther = (CharacterShortcutsId) other;

        return (this.getCharObjId() == castOther.getCharObjId())
            && (this.getSlot() == castOther.getSlot()) && (this.getPage() == castOther.getPage())
            && (this.getClassIndex() == castOther.getClassIndex());
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + this.getCharObjId();
        result = 37 * result + this.getSlot();
        result = 37 * result + this.getPage();
        result = 37 * result + this.getClassIndex();
        return result;
    }

}
