package net.sf.l2j.loginserver.beans;

// Generated 7 déc. 2006 18:49:51 by Hibernate Tools 3.2.0.beta8

/**
 * CharacterRecipebookId generated by hbm2java
 */
public class CharacterRecipebookId implements java.io.Serializable
{

    // Fields    

    private long id;
    private long charId;

    // Constructors

    /** default constructor */
    public CharacterRecipebookId()
    {
    }

    /** full constructor */
    public CharacterRecipebookId(long id, long charId)
    {
        this.id = id;
        this.charId = charId;
    }

    // Property accessors
    public long getId()
    {
        return this.id;
    }

    public void setId(long id)
    {
        this.id = id;
    }

    public long getCharId()
    {
        return this.charId;
    }

    public void setCharId(long charId)
    {
        this.charId = charId;
    }

    public boolean equals(Object other)
    {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof CharacterRecipebookId)) return false;
        CharacterRecipebookId castOther = (CharacterRecipebookId) other;

        return (this.getId() == castOther.getId()) && (this.getCharId() == castOther.getCharId());
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + (int) this.getId();
        result = 37 * result + (int) this.getCharId();
        return result;
    }

}
