package net.sf.l2j.loginserver.beans;

// Generated 11 déc. 2006 17:28:16 by Hibernate Tools 3.2.0.beta8

/**
 * CharacterSkillsSave generated by hbm2java
 */
public class CharacterSkillsSave implements java.io.Serializable
{

    // Fields    

    private CharacterSkillsSaveId id;
    private Characters characters;
    private int skillLevel;
    private int effectCount;
    private int effectCurTime;
    private int reuseDelay;
    private int restoreType;

    // Constructors

    /** default constructor */
    public CharacterSkillsSave()
    {
    }

    /** full constructor */
    public CharacterSkillsSave(CharacterSkillsSaveId id, Characters characters, int skillLevel,
                               int effectCount, int effectCurTime, int reuseDelay, int restoreType)
    {
        this.id = id;
        this.characters = characters;
        this.skillLevel = skillLevel;
        this.effectCount = effectCount;
        this.effectCurTime = effectCurTime;
        this.reuseDelay = reuseDelay;
        this.restoreType = restoreType;
    }

    // Property accessors
    public CharacterSkillsSaveId getId()
    {
        return this.id;
    }

    public void setId(CharacterSkillsSaveId id)
    {
        this.id = id;
    }

    public Characters getCharacters()
    {
        return this.characters;
    }

    public void setCharacters(Characters characters)
    {
        this.characters = characters;
    }

    public int getSkillLevel()
    {
        return this.skillLevel;
    }

    public void setSkillLevel(int skillLevel)
    {
        this.skillLevel = skillLevel;
    }

    public int getEffectCount()
    {
        return this.effectCount;
    }

    public void setEffectCount(int effectCount)
    {
        this.effectCount = effectCount;
    }

    public int getEffectCurTime()
    {
        return this.effectCurTime;
    }

    public void setEffectCurTime(int effectCurTime)
    {
        this.effectCurTime = effectCurTime;
    }

    public int getReuseDelay()
    {
        return this.reuseDelay;
    }

    public void setReuseDelay(int reuseDelay)
    {
        this.reuseDelay = reuseDelay;
    }

    public int getRestoreType()
    {
        return this.restoreType;
    }

    public void setRestoreType(int restoreType)
    {
        this.restoreType = restoreType;
    }

}
