package net.sf.l2j.loginserver.beans;

// Generated 7 déc. 2006 18:49:51 by Hibernate Tools 3.2.0.beta8

/**
 * CharacterShortcuts generated by hbm2java
 */
public class CharacterShortcuts implements java.io.Serializable
{

    // Fields    

    private CharacterShortcutsId id;
    private Short type;
    private Long shortcutId;
    private String level;

    // Constructors

    /** default constructor */
    public CharacterShortcuts()
    {
    }

    /** minimal constructor */
    public CharacterShortcuts(CharacterShortcutsId id)
    {
        this.id = id;
    }

    /** full constructor */
    public CharacterShortcuts(CharacterShortcutsId id, Short type, Long shortcutId, String level)
    {
        this.id = id;
        this.type = type;
        this.shortcutId = shortcutId;
        this.level = level;
    }

    // Property accessors
    public CharacterShortcutsId getId()
    {
        return this.id;
    }

    public void setId(CharacterShortcutsId id)
    {
        this.id = id;
    }

    public Short getType()
    {
        return this.type;
    }

    public void setType(Short type)
    {
        this.type = type;
    }

    public Long getShortcutId()
    {
        return this.shortcutId;
    }

    public void setShortcutId(Long shortcutId)
    {
        this.shortcutId = shortcutId;
    }

    public String getLevel()
    {
        return this.level;
    }

    public void setLevel(String level)
    {
        this.level = level;
    }

}
