package net.sf.l2j.loginserver.beans;

// Generated 11 déc. 2006 17:28:16 by Hibernate Tools 3.2.0.beta8

/**
 * CharacterFriendsId generated by hbm2java
 */
public class CharacterFriendsId implements java.io.Serializable
{

    // Fields    

    private int charId;
    private String friendName;

    // Constructors

    /** default constructor */
    public CharacterFriendsId()
    {
    }

    /** full constructor */
    public CharacterFriendsId(int charId, String friendName)
    {
        this.charId = charId;
        this.friendName = friendName;
    }

    // Property accessors
    public int getCharId()
    {
        return this.charId;
    }

    public void setCharId(int charId)
    {
        this.charId = charId;
    }

    public String getFriendName()
    {
        return this.friendName;
    }

    public void setFriendName(String friendName)
    {
        this.friendName = friendName;
    }

    public boolean equals(Object other)
    {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof CharacterFriendsId)) return false;
        CharacterFriendsId castOther = (CharacterFriendsId) other;

        return (this.getCharId() == castOther.getCharId())
            && ((this.getFriendName() == castOther.getFriendName()) || (this.getFriendName() != null
                && castOther.getFriendName() != null && this.getFriendName().equals(
                                                                                    castOther.getFriendName())));
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + this.getCharId();
        result = 37 * result + (getFriendName() == null ? 0 : this.getFriendName().hashCode());
        return result;
    }

}
