package net.sf.l2j.loginserver.beans;

// Generated 7 déc. 2006 18:49:51 by Hibernate Tools 3.2.0.beta8

/**
 * CharacterHennas generated by hbm2java
 */
public class CharacterHennas implements java.io.Serializable
{

    // Fields    

    private CharacterHennasId id;
    private Integer symbolId;

    // Constructors

    /** default constructor */
    public CharacterHennas()
    {
    }

    /** minimal constructor */
    public CharacterHennas(CharacterHennasId id)
    {
        this.id = id;
    }

    /** full constructor */
    public CharacterHennas(CharacterHennasId id, Integer symbolId)
    {
        this.id = id;
        this.symbolId = symbolId;
    }

    // Property accessors
    public CharacterHennasId getId()
    {
        return this.id;
    }

    public void setId(CharacterHennasId id)
    {
        this.id = id;
    }

    public Integer getSymbolId()
    {
        return this.symbolId;
    }

    public void setSymbolId(Integer symbolId)
    {
        this.symbolId = symbolId;
    }

}
