package net.sf.l2j.loginserver.beans;

// Generated 7 déc. 2006 18:49:51 by Hibernate Tools 3.2.0.beta8

/**
 * CharacterSubclassesId generated by hbm2java
 */
public class CharacterSubclassesId implements java.io.Serializable
{

    // Fields    

    private long charObjId;
    private int classId;

    // Constructors

    /** default constructor */
    public CharacterSubclassesId()
    {
    }

    /** full constructor */
    public CharacterSubclassesId(long charObjId, int classId)
    {
        this.charObjId = charObjId;
        this.classId = classId;
    }

    // Property accessors
    public long getCharObjId()
    {
        return this.charObjId;
    }

    public void setCharObjId(long charObjId)
    {
        this.charObjId = charObjId;
    }

    public int getClassId()
    {
        return this.classId;
    }

    public void setClassId(int classId)
    {
        this.classId = classId;
    }

    public boolean equals(Object other)
    {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof CharacterSubclassesId)) return false;
        CharacterSubclassesId castOther = (CharacterSubclassesId) other;

        return (this.getCharObjId() == castOther.getCharObjId())
            && (this.getClassId() == castOther.getClassId());
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + (int) this.getCharObjId();
        result = 37 * result + this.getClassId();
        return result;
    }

}
