package net.sf.l2j.loginserver.beans;

// Generated 7 déc. 2006 18:49:51 by Hibernate Tools 3.2.0.beta8

/**
 * CharacterMacrosesId generated by hbm2java
 */
public class CharacterMacrosesId implements java.io.Serializable
{

    // Fields    

    private int charObjId;
    private int id;

    // Constructors

    /** default constructor */
    public CharacterMacrosesId()
    {
    }

    /** full constructor */
    public CharacterMacrosesId(int charObjId, int id)
    {
        this.charObjId = charObjId;
        this.id = id;
    }

    // Property accessors
    public int getCharObjId()
    {
        return this.charObjId;
    }

    public void setCharObjId(int charObjId)
    {
        this.charObjId = charObjId;
    }

    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    public boolean equals(Object other)
    {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof CharacterMacrosesId)) return false;
        CharacterMacrosesId castOther = (CharacterMacrosesId) other;

        return (this.getCharObjId() == castOther.getCharObjId()) && (this.getId() == castOther.getId());
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + this.getCharObjId();
        result = 37 * result + this.getId();
        return result;
    }

}
