package net.sf.l2j.loginserver.beans;

// Generated 11 déc. 2006 17:28:16 by Hibernate Tools 3.2.0.beta8

/**
 * CharacterQuestsId generated by hbm2java
 */
public class CharacterQuestsId implements java.io.Serializable
{

    // Fields    

    private int charId;
    private String name;
    private String var;
    private int classIndex;

    // Constructors

    /** default constructor */
    public CharacterQuestsId()
    {
    }

    /** full constructor */
    public CharacterQuestsId(int charId, String name, String var, int classIndex)
    {
        this.charId = charId;
        this.name = name;
        this.var = var;
        this.classIndex = classIndex;
    }

    // Property accessors
    public int getCharId()
    {
        return this.charId;
    }

    public void setCharId(int charId)
    {
        this.charId = charId;
    }

    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public String getVar()
    {
        return this.var;
    }

    public void setVar(String var)
    {
        this.var = var;
    }

    public int getClassIndex()
    {
        return this.classIndex;
    }

    public void setClassIndex(int classIndex)
    {
        this.classIndex = classIndex;
    }

    public boolean equals(Object other)
    {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof CharacterQuestsId)) return false;
        CharacterQuestsId castOther = (CharacterQuestsId) other;

        return (this.getCharId() == castOther.getCharId())
            && ((this.getName() == castOther.getName()) || (this.getName() != null
                && castOther.getName() != null && this.getName().equals(castOther.getName())))
            && ((this.getVar() == castOther.getVar()) || (this.getVar() != null
                && castOther.getVar() != null && this.getVar().equals(castOther.getVar())))
            && (this.getClassIndex() == castOther.getClassIndex());
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + this.getCharId();
        result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
        result = 37 * result + (getVar() == null ? 0 : this.getVar().hashCode());
        result = 37 * result + this.getClassIndex();
        return result;
    }

}
