package net.sf.l2j.loginserver.beans;

// Generated 11 déc. 2006 17:28:16 by Hibernate Tools 3.2.0.beta8

/**
 * CharacterMacroses generated by hbm2java
 */
public class CharacterMacroses implements java.io.Serializable
{

    // Fields    

    private CharacterMacrosesId id;
    private Characters characters;
    private Integer icon;
    private String name;
    private String descr;
    private String acronym;
    private String commands;

    // Constructors

    /** default constructor */
    public CharacterMacroses()
    {
    }

    /** minimal constructor */
    public CharacterMacroses(CharacterMacrosesId id, Characters characters)
    {
        this.id = id;
        this.characters = characters;
    }

    /** full constructor */
    public CharacterMacroses(CharacterMacrosesId id, Characters characters, Integer icon, String name,
                             String descr, String acronym, String commands)
    {
        this.id = id;
        this.characters = characters;
        this.icon = icon;
        this.name = name;
        this.descr = descr;
        this.acronym = acronym;
        this.commands = commands;
    }

    // Property accessors
    public CharacterMacrosesId getId()
    {
        return this.id;
    }

    public void setId(CharacterMacrosesId id)
    {
        this.id = id;
    }

    public Characters getCharacters()
    {
        return this.characters;
    }

    public void setCharacters(Characters characters)
    {
        this.characters = characters;
    }

    public Integer getIcon()
    {
        return this.icon;
    }

    public void setIcon(Integer icon)
    {
        this.icon = icon;
    }

    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public String getDescr()
    {
        return this.descr;
    }

    public void setDescr(String descr)
    {
        this.descr = descr;
    }

    public String getAcronym()
    {
        return this.acronym;
    }

    public void setAcronym(String acronym)
    {
        this.acronym = acronym;
    }

    public String getCommands()
    {
        return this.commands;
    }

    public void setCommands(String commands)
    {
        this.commands = commands;
    }

}
