package net.sf.l2j.loginserver.beans;

// Generated 7 déc. 2006 18:49:51 by Hibernate Tools 3.2.0.beta8

/**
 * CharacterHennasId generated by hbm2java
 */
public class CharacterHennasId implements java.io.Serializable
{

    // Fields    

    private int charObjId;
    private int slot;
    private int classIndex;

    // Constructors

    /** default constructor */
    public CharacterHennasId()
    {
    }

    /** full constructor */
    public CharacterHennasId(int charObjId, int slot, int classIndex)
    {
        this.charObjId = charObjId;
        this.slot = slot;
        this.classIndex = classIndex;
    }

    // Property accessors
    public int getCharObjId()
    {
        return this.charObjId;
    }

    public void setCharObjId(int charObjId)
    {
        this.charObjId = charObjId;
    }

    public int getSlot()
    {
        return this.slot;
    }

    public void setSlot(int slot)
    {
        this.slot = slot;
    }

    public int getClassIndex()
    {
        return this.classIndex;
    }

    public void setClassIndex(int classIndex)
    {
        this.classIndex = classIndex;
    }

    public boolean equals(Object other)
    {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof CharacterHennasId)) return false;
        CharacterHennasId castOther = (CharacterHennasId) other;

        return (this.getCharObjId() == castOther.getCharObjId())
            && (this.getSlot() == castOther.getSlot())
            && (this.getClassIndex() == castOther.getClassIndex());
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + this.getCharObjId();
        result = 37 * result + this.getSlot();
        result = 37 * result + this.getClassIndex();
        return result;
    }

}
