package net.sf.l2j.loginserver.beans;

// Generated 7 déc. 2006 18:49:51 by Hibernate Tools 3.2.0.beta8

/**
 * CharacterFriends generated by hbm2java
 */
public class CharacterFriends implements java.io.Serializable
{

    // Fields    

    private CharacterFriendsId id;
    private int friendId;

    // Constructors

    /** default constructor */
    public CharacterFriends()
    {
    }

    /** full constructor */
    public CharacterFriends(CharacterFriendsId id, int friendId)
    {
        this.id = id;
        this.friendId = friendId;
    }

    // Property accessors
    public CharacterFriendsId getId()
    {
        return this.id;
    }

    public void setId(CharacterFriendsId id)
    {
        this.id = id;
    }

    public int getFriendId()
    {
        return this.friendId;
    }

    public void setFriendId(int friendId)
    {
        this.friendId = friendId;
    }

}
