package net.sf.l2j.loginserver.beans;

// Generated 7 déc. 2006 18:49:51 by Hibernate Tools 3.2.0.beta8

/**
 * ClanData generated by hbm2java
 */
public class ClanData implements java.io.Serializable
{

    // Fields    

    private int clanId;
    private String clanName;
    private Integer clanLevel;
    private Integer hasCastle;
    private Integer hasHideout;
    private Integer allyId;
    private String allyName;
    private Integer leaderId;
    private Integer crestId;
    private Integer crestLargeId;
    private Integer allyCrestId;
    private int reputationScore;
    private int rank;
    private int auctionBidAt;

    // Constructors

    /** default constructor */
    public ClanData()
    {
    }

    /** minimal constructor */
    public ClanData(int clanId, int reputationScore, int rank, int auctionBidAt)
    {
        this.clanId = clanId;
        this.reputationScore = reputationScore;
        this.rank = rank;
        this.auctionBidAt = auctionBidAt;
    }

    /** full constructor */
    public ClanData(int clanId, String clanName, Integer clanLevel, Integer hasCastle,
                    Integer hasHideout, Integer allyId, String allyName, Integer leaderId,
                    Integer crestId, Integer crestLargeId, Integer allyCrestId, int reputationScore,
                    int rank, int auctionBidAt)
    {
        this.clanId = clanId;
        this.clanName = clanName;
        this.clanLevel = clanLevel;
        this.hasCastle = hasCastle;
        this.hasHideout = hasHideout;
        this.allyId = allyId;
        this.allyName = allyName;
        this.leaderId = leaderId;
        this.crestId = crestId;
        this.crestLargeId = crestLargeId;
        this.allyCrestId = allyCrestId;
        this.reputationScore = reputationScore;
        this.rank = rank;
        this.auctionBidAt = auctionBidAt;
    }

    // Property accessors
    public int getClanId()
    {
        return this.clanId;
    }

    public void setClanId(int clanId)
    {
        this.clanId = clanId;
    }

    public String getClanName()
    {
        return this.clanName;
    }

    public void setClanName(String clanName)
    {
        this.clanName = clanName;
    }

    public Integer getClanLevel()
    {
        return this.clanLevel;
    }

    public void setClanLevel(Integer clanLevel)
    {
        this.clanLevel = clanLevel;
    }

    public Integer getHasCastle()
    {
        return this.hasCastle;
    }

    public void setHasCastle(Integer hasCastle)
    {
        this.hasCastle = hasCastle;
    }

    public Integer getHasHideout()
    {
        return this.hasHideout;
    }

    public void setHasHideout(Integer hasHideout)
    {
        this.hasHideout = hasHideout;
    }

    public Integer getAllyId()
    {
        return this.allyId;
    }

    public void setAllyId(Integer allyId)
    {
        this.allyId = allyId;
    }

    public String getAllyName()
    {
        return this.allyName;
    }

    public void setAllyName(String allyName)
    {
        this.allyName = allyName;
    }

    public Integer getLeaderId()
    {
        return this.leaderId;
    }

    public void setLeaderId(Integer leaderId)
    {
        this.leaderId = leaderId;
    }

    public Integer getCrestId()
    {
        return this.crestId;
    }

    public void setCrestId(Integer crestId)
    {
        this.crestId = crestId;
    }

    public Integer getCrestLargeId()
    {
        return this.crestLargeId;
    }

    public void setCrestLargeId(Integer crestLargeId)
    {
        this.crestLargeId = crestLargeId;
    }

    public Integer getAllyCrestId()
    {
        return this.allyCrestId;
    }

    public void setAllyCrestId(Integer allyCrestId)
    {
        this.allyCrestId = allyCrestId;
    }

    public int getReputationScore()
    {
        return this.reputationScore;
    }

    public void setReputationScore(int reputationScore)
    {
        this.reputationScore = reputationScore;
    }

    public int getRank()
    {
        return this.rank;
    }

    public void setRank(int rank)
    {
        this.rank = rank;
    }

    public int getAuctionBidAt()
    {
        return this.auctionBidAt;
    }

    public void setAuctionBidAt(int auctionBidAt)
    {
        this.auctionBidAt = auctionBidAt;
    }

}
