package net.sf.l2j.loginserver.beans;

// Generated 7 déc. 2006 18:49:51 by Hibernate Tools 3.2.0.beta8

/**
 * ClanPrivs generated by hbm2java
 */
public class ClanPrivs implements java.io.Serializable
{

    // Fields    

    private ClanPrivsId id;
    private int privilleges;

    // Constructors

    /** default constructor */
    public ClanPrivs()
    {
    }

    /** full constructor */
    public ClanPrivs(ClanPrivsId id, int privilleges)
    {
        this.id = id;
        this.privilleges = privilleges;
    }

    // Property accessors
    public ClanPrivsId getId()
    {
        return this.id;
    }

    public void setId(ClanPrivsId id)
    {
        this.id = id;
    }

    public int getPrivilleges()
    {
        return this.privilleges;
    }

    public void setPrivilleges(int privilleges)
    {
        this.privilleges = privilleges;
    }

}
