package net.sf.l2j.loginserver.beans;

// Generated 11 déc. 2006 17:28:16 by Hibernate Tools 3.2.0.beta8

/**
 * ClanPrivs generated by hbm2java
 */
public class ClanPrivs implements java.io.Serializable
{

    // Fields    

    private ClanPrivsId id;
    private ClanData clanData;
    private int privilleges;

    // Constructors

    /** default constructor */
    public ClanPrivs()
    {
    }

    /** full constructor */
    public ClanPrivs(ClanPrivsId id, ClanData clanData, int privilleges)
    {
        this.id = id;
        this.clanData = clanData;
        this.privilleges = privilleges;
    }

    // Property accessors
    public ClanPrivsId getId()
    {
        return this.id;
    }

    public void setId(ClanPrivsId id)
    {
        this.id = id;
    }

    public ClanData getClanData()
    {
        return this.clanData;
    }

    public void setClanData(ClanData clanData)
    {
        this.clanData = clanData;
    }

    public int getPrivilleges()
    {
        return this.privilleges;
    }

    public void setPrivilleges(int privilleges)
    {
        this.privilleges = privilleges;
    }

}
