package net.sf.l2j.loginserver.beans;

// Generated 7 déc. 2006 18:49:51 by Hibernate Tools 3.2.0.beta8

/**
 * ClanPrivsId generated by hbm2java
 */
public class ClanPrivsId implements java.io.Serializable
{

    // Fields    

    private int clanId;
    private int rank;
    private int party;

    // Constructors

    /** default constructor */
    public ClanPrivsId()
    {
    }

    /** full constructor */
    public ClanPrivsId(int clanId, int rank, int party)
    {
        this.clanId = clanId;
        this.rank = rank;
        this.party = party;
    }

    // Property accessors
    public int getClanId()
    {
        return this.clanId;
    }

    public void setClanId(int clanId)
    {
        this.clanId = clanId;
    }

    public int getRank()
    {
        return this.rank;
    }

    public void setRank(int rank)
    {
        this.rank = rank;
    }

    public int getParty()
    {
        return this.party;
    }

    public void setParty(int party)
    {
        this.party = party;
    }

    public boolean equals(Object other)
    {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof ClanPrivsId)) return false;
        ClanPrivsId castOther = (ClanPrivsId) other;

        return (this.getClanId() == castOther.getClanId()) && (this.getRank() == castOther.getRank())
            && (this.getParty() == castOther.getParty());
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + this.getClanId();
        result = 37 * result + this.getRank();
        result = 37 * result + this.getParty();
        return result;
    }

}
