package net.sf.l2j.loginserver.beans;

// Generated 7 déc. 2006 18:49:51 by Hibernate Tools 3.2.0.beta8

/**
 * ClanSubpledges generated by hbm2java
 */
public class ClanSubpledges implements java.io.Serializable
{

    // Fields    

    private ClanSubpledgesId id;
    private String name;
    private String leaderName;

    // Constructors

    /** default constructor */
    public ClanSubpledges()
    {
    }

    /** minimal constructor */
    public ClanSubpledges(ClanSubpledgesId id)
    {
        this.id = id;
    }

    /** full constructor */
    public ClanSubpledges(ClanSubpledgesId id, String name, String leaderName)
    {
        this.id = id;
        this.name = name;
        this.leaderName = leaderName;
    }

    // Property accessors
    public ClanSubpledgesId getId()
    {
        return this.id;
    }

    public void setId(ClanSubpledgesId id)
    {
        this.id = id;
    }

    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public String getLeaderName()
    {
        return this.leaderName;
    }

    public void setLeaderName(String leaderName)
    {
        this.leaderName = leaderName;
    }

}
