package net.sf.l2j.loginserver.beans;

// Generated 7 déc. 2006 18:49:51 by Hibernate Tools 3.2.0.beta8

/**
 * ClanhallFunctionsId generated by hbm2java
 */
public class ClanhallFunctionsId implements java.io.Serializable
{

    // Fields    

    private int hallId;
    private int type;

    // Constructors

    /** default constructor */
    public ClanhallFunctionsId()
    {
    }

    /** full constructor */
    public ClanhallFunctionsId(int hallId, int type)
    {
        this.hallId = hallId;
        this.type = type;
    }

    // Property accessors
    public int getHallId()
    {
        return this.hallId;
    }

    public void setHallId(int hallId)
    {
        this.hallId = hallId;
    }

    public int getType()
    {
        return this.type;
    }

    public void setType(int type)
    {
        this.type = type;
    }

    public boolean equals(Object other)
    {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof ClanhallFunctionsId)) return false;
        ClanhallFunctionsId castOther = (ClanhallFunctionsId) other;

        return (this.getHallId() == castOther.getHallId()) && (this.getType() == castOther.getType());
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + this.getHallId();
        result = 37 * result + this.getType();
        return result;
    }

}
