package net.sf.l2j.loginserver.beans;

// Generated 11 déc. 2006 17:28:16 by Hibernate Tools 3.2.0.beta8

/**
 * ClanWars generated by hbm2java
 */
public class ClanWars implements java.io.Serializable
{

    // Fields    

    private ClanWarsId id;

    // Constructors

    /** default constructor */
    public ClanWars()
    {
    }

    /** full constructor */
    public ClanWars(ClanWarsId id)
    {
        this.id = id;
    }

    // Property accessors
    public ClanWarsId getId()
    {
        return this.id;
    }

    public void setId(ClanWarsId id)
    {
        this.id = id;
    }

}
