package net.sf.l2j.loginserver.beans;

// Generated 11 déc. 2006 17:28:16 by Hibernate Tools 3.2.0.beta8

/**
 * ClanWarsId generated by hbm2java
 */
public class ClanWarsId implements java.io.Serializable
{

    // Fields    

    private String clan1;
    private String clan2;
    private boolean wantspeace1;
    private boolean wantspeace2;

    // Constructors

    /** default constructor */
    public ClanWarsId()
    {
    }

    /** full constructor */
    public ClanWarsId(String clan1, String clan2, boolean wantspeace1, boolean wantspeace2)
    {
        this.clan1 = clan1;
        this.clan2 = clan2;
        this.wantspeace1 = wantspeace1;
        this.wantspeace2 = wantspeace2;
    }

    // Property accessors
    public String getClan1()
    {
        return this.clan1;
    }

    public void setClan1(String clan1)
    {
        this.clan1 = clan1;
    }

    public String getClan2()
    {
        return this.clan2;
    }

    public void setClan2(String clan2)
    {
        this.clan2 = clan2;
    }

    public boolean isWantspeace1()
    {
        return this.wantspeace1;
    }

    public void setWantspeace1(boolean wantspeace1)
    {
        this.wantspeace1 = wantspeace1;
    }

    public boolean isWantspeace2()
    {
        return this.wantspeace2;
    }

    public void setWantspeace2(boolean wantspeace2)
    {
        this.wantspeace2 = wantspeace2;
    }

    public boolean equals(Object other)
    {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof ClanWarsId)) return false;
        ClanWarsId castOther = (ClanWarsId) other;

        return ((this.getClan1() == castOther.getClan1()) || (this.getClan1() != null
            && castOther.getClan1() != null && this.getClan1().equals(castOther.getClan1())))
            && ((this.getClan2() == castOther.getClan2()) || (this.getClan2() != null
                && castOther.getClan2() != null && this.getClan2().equals(castOther.getClan2())))
            && (this.isWantspeace1() == castOther.isWantspeace1())
            && (this.isWantspeace2() == castOther.isWantspeace2());
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + (getClan1() == null ? 0 : this.getClan1().hashCode());
        result = 37 * result + (getClan2() == null ? 0 : this.getClan2().hashCode());
        result = 37 * result + (this.isWantspeace1() ? 1 : 0);
        result = 37 * result + (this.isWantspeace2() ? 1 : 0);
        return result;
    }

}
