package net.sf.l2j.loginserver.beans;

// Generated 7 déc. 2006 18:49:51 by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;

/**
 * ClanhallFunctions generated by hbm2java
 */
public class ClanhallFunctions implements java.io.Serializable
{

    // Fields    

    private ClanhallFunctionsId id;
    private int lvl;
    private int lease;
    private BigDecimal rate;
    private BigDecimal endTime;
    private int inDebt;

    // Constructors

    /** default constructor */
    public ClanhallFunctions()
    {
    }

    /** full constructor */
    public ClanhallFunctions(ClanhallFunctionsId id, int lvl, int lease, BigDecimal rate,
                             BigDecimal endTime, int inDebt)
    {
        this.id = id;
        this.lvl = lvl;
        this.lease = lease;
        this.rate = rate;
        this.endTime = endTime;
        this.inDebt = inDebt;
    }

    // Property accessors
    public ClanhallFunctionsId getId()
    {
        return this.id;
    }

    public void setId(ClanhallFunctionsId id)
    {
        this.id = id;
    }

    public int getLvl()
    {
        return this.lvl;
    }

    public void setLvl(int lvl)
    {
        this.lvl = lvl;
    }

    public int getLease()
    {
        return this.lease;
    }

    public void setLease(int lease)
    {
        this.lease = lease;
    }

    public BigDecimal getRate()
    {
        return this.rate;
    }

    public void setRate(BigDecimal rate)
    {
        this.rate = rate;
    }

    public BigDecimal getEndTime()
    {
        return this.endTime;
    }

    public void setEndTime(BigDecimal endTime)
    {
        this.endTime = endTime;
    }

    public int getInDebt()
    {
        return this.inDebt;
    }

    public void setInDebt(int inDebt)
    {
        this.inDebt = inDebt;
    }

}
