package net.sf.l2j.loginserver.beans;

// Generated 7 déc. 2006 18:49:51 by Hibernate Tools 3.2.0.beta8

/**
 * ClanSkills generated by hbm2java
 */
public class ClanSkills implements java.io.Serializable
{

    // Fields    

    private ClanSkillsId id;
    private int skillLevel;
    private String skillName;

    // Constructors

    /** default constructor */
    public ClanSkills()
    {
    }

    /** minimal constructor */
    public ClanSkills(ClanSkillsId id, int skillLevel)
    {
        this.id = id;
        this.skillLevel = skillLevel;
    }

    /** full constructor */
    public ClanSkills(ClanSkillsId id, int skillLevel, String skillName)
    {
        this.id = id;
        this.skillLevel = skillLevel;
        this.skillName = skillName;
    }

    // Property accessors
    public ClanSkillsId getId()
    {
        return this.id;
    }

    public void setId(ClanSkillsId id)
    {
        this.id = id;
    }

    public int getSkillLevel()
    {
        return this.skillLevel;
    }

    public void setSkillLevel(int skillLevel)
    {
        this.skillLevel = skillLevel;
    }

    public String getSkillName()
    {
        return this.skillName;
    }

    public void setSkillName(String skillName)
    {
        this.skillName = skillName;
    }

}
