package net.sf.l2j.loginserver.beans;

// Generated 7 déc. 2006 18:49:51 by Hibernate Tools 3.2.0.beta8

/**
 * ClanhallId generated by hbm2java
 */
public class ClanhallId implements java.io.Serializable
{

    // Fields    

    private int id;
    private String name;

    // Constructors

    /** default constructor */
    public ClanhallId()
    {
    }

    /** full constructor */
    public ClanhallId(int id, String name)
    {
        this.id = id;
        this.name = name;
    }

    // Property accessors
    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public boolean equals(Object other)
    {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof ClanhallId)) return false;
        ClanhallId castOther = (ClanhallId) other;

        return (this.getId() == castOther.getId())
            && ((this.getName() == castOther.getName()) || (this.getName() != null
                && castOther.getName() != null && this.getName().equals(castOther.getName())));
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + this.getId();
        result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
        return result;
    }

}
