package net.sf.l2j.loginserver.beans;

// Generated 11 déc. 2006 17:28:16 by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * ClanData generated by hbm2java
 */
public class ClanData implements java.io.Serializable
{

    // Fields    

    private int clanId;
    private Characters characters;
    private String clanName;
    private Integer clanLevel;
    private Integer hasCastle;
    private Integer hasHideout;
    private Integer allyId;
    private String allyName;
    private Integer crestId;
    private Integer crestLargeId;
    private Integer allyCrestId;
    private int reputationScore;
    private int rank;
    private int auctionBidAt;
    private Set<ClanSkills> clanSkillses = new HashSet<ClanSkills>(0);
    private Set<ClanPrivs> clanPrivses = new HashSet<ClanPrivs>(0);

    // Constructors

    /** default constructor */
    public ClanData()
    {
    }

    /** minimal constructor */
    public ClanData(int clanId, int reputationScore, int rank, int auctionBidAt)
    {
        this.clanId = clanId;
        this.reputationScore = reputationScore;
        this.rank = rank;
        this.auctionBidAt = auctionBidAt;
    }

    /** full constructor */
    public ClanData(int clanId, Characters characters, String clanName, Integer clanLevel,
                    Integer hasCastle, Integer hasHideout, Integer allyId, String allyName,
                    Integer crestId, Integer crestLargeId, Integer allyCrestId, int reputationScore,
                    int rank, int auctionBidAt, Set<ClanSkills> clanSkillses, Set<ClanPrivs> clanPrivses)
    {
        this.clanId = clanId;
        this.characters = characters;
        this.clanName = clanName;
        this.clanLevel = clanLevel;
        this.hasCastle = hasCastle;
        this.hasHideout = hasHideout;
        this.allyId = allyId;
        this.allyName = allyName;
        this.crestId = crestId;
        this.crestLargeId = crestLargeId;
        this.allyCrestId = allyCrestId;
        this.reputationScore = reputationScore;
        this.rank = rank;
        this.auctionBidAt = auctionBidAt;
        this.clanSkillses = clanSkillses;
        this.clanPrivses = clanPrivses;
    }

    // Property accessors
    public int getClanId()
    {
        return this.clanId;
    }

    public void setClanId(int clanId)
    {
        this.clanId = clanId;
    }

    public Characters getCharacters()
    {
        return this.characters;
    }

    public void setCharacters(Characters characters)
    {
        this.characters = characters;
    }

    public String getClanName()
    {
        return this.clanName;
    }

    public void setClanName(String clanName)
    {
        this.clanName = clanName;
    }

    public Integer getClanLevel()
    {
        return this.clanLevel;
    }

    public void setClanLevel(Integer clanLevel)
    {
        this.clanLevel = clanLevel;
    }

    public Integer getHasCastle()
    {
        return this.hasCastle;
    }

    public void setHasCastle(Integer hasCastle)
    {
        this.hasCastle = hasCastle;
    }

    public Integer getHasHideout()
    {
        return this.hasHideout;
    }

    public void setHasHideout(Integer hasHideout)
    {
        this.hasHideout = hasHideout;
    }

    public Integer getAllyId()
    {
        return this.allyId;
    }

    public void setAllyId(Integer allyId)
    {
        this.allyId = allyId;
    }

    public String getAllyName()
    {
        return this.allyName;
    }

    public void setAllyName(String allyName)
    {
        this.allyName = allyName;
    }

    public Integer getCrestId()
    {
        return this.crestId;
    }

    public void setCrestId(Integer crestId)
    {
        this.crestId = crestId;
    }

    public Integer getCrestLargeId()
    {
        return this.crestLargeId;
    }

    public void setCrestLargeId(Integer crestLargeId)
    {
        this.crestLargeId = crestLargeId;
    }

    public Integer getAllyCrestId()
    {
        return this.allyCrestId;
    }

    public void setAllyCrestId(Integer allyCrestId)
    {
        this.allyCrestId = allyCrestId;
    }

    public int getReputationScore()
    {
        return this.reputationScore;
    }

    public void setReputationScore(int reputationScore)
    {
        this.reputationScore = reputationScore;
    }

    public int getRank()
    {
        return this.rank;
    }

    public void setRank(int rank)
    {
        this.rank = rank;
    }

    public int getAuctionBidAt()
    {
        return this.auctionBidAt;
    }

    public void setAuctionBidAt(int auctionBidAt)
    {
        this.auctionBidAt = auctionBidAt;
    }

    public Set<ClanSkills> getClanSkillses()
    {
        return this.clanSkillses;
    }

    public void setClanSkillses(Set<ClanSkills> clanSkillses)
    {
        this.clanSkillses = clanSkillses;
    }

    public Set<ClanPrivs> getClanPrivses()
    {
        return this.clanPrivses;
    }

    public void setClanPrivses(Set<ClanPrivs> clanPrivses)
    {
        this.clanPrivses = clanPrivses;
    }

}
