package net.sf.l2j.loginserver.beans;

// Generated 7 déc. 2006 18:49:51 by Hibernate Tools 3.2.0.beta8

/**
 * ClanSkillsId generated by hbm2java
 */
public class ClanSkillsId implements java.io.Serializable
{

    // Fields    

    private int clanId;
    private int skillId;

    // Constructors

    /** default constructor */
    public ClanSkillsId()
    {
    }

    /** full constructor */
    public ClanSkillsId(int clanId, int skillId)
    {
        this.clanId = clanId;
        this.skillId = skillId;
    }

    // Property accessors
    public int getClanId()
    {
        return this.clanId;
    }

    public void setClanId(int clanId)
    {
        this.clanId = clanId;
    }

    public int getSkillId()
    {
        return this.skillId;
    }

    public void setSkillId(int skillId)
    {
        this.skillId = skillId;
    }

    public boolean equals(Object other)
    {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof ClanSkillsId)) return false;
        ClanSkillsId castOther = (ClanSkillsId) other;

        return (this.getClanId() == castOther.getClanId())
            && (this.getSkillId() == castOther.getSkillId());
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + this.getClanId();
        result = 37 * result + this.getSkillId();
        return result;
    }

}
