package net.sf.l2j.loginserver.beans;

// Generated 11 déc. 2006 17:28:16 by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;

/**
 * Clanhall generated by hbm2java
 */
public class Clanhall implements java.io.Serializable
{

    // Fields    

    private ClanhallId id;
    private int ownerId;
    private int lease;
    private String desc;
    private String location;
    private BigDecimal paidUntil;
    private boolean grade;

    // Constructors

    /** default constructor */
    public Clanhall()
    {
    }

    /** full constructor */
    public Clanhall(ClanhallId id, int ownerId, int lease, String desc, String location,
                    BigDecimal paidUntil, boolean grade)
    {
        this.id = id;
        this.ownerId = ownerId;
        this.lease = lease;
        this.desc = desc;
        this.location = location;
        this.paidUntil = paidUntil;
        this.grade = grade;
    }

    // Property accessors
    public ClanhallId getId()
    {
        return this.id;
    }

    public void setId(ClanhallId id)
    {
        this.id = id;
    }

    public int getOwnerId()
    {
        return this.ownerId;
    }

    public void setOwnerId(int ownerId)
    {
        this.ownerId = ownerId;
    }

    public int getLease()
    {
        return this.lease;
    }

    public void setLease(int lease)
    {
        this.lease = lease;
    }

    public String getDesc()
    {
        return this.desc;
    }

    public void setDesc(String desc)
    {
        this.desc = desc;
    }

    public String getLocation()
    {
        return this.location;
    }

    public void setLocation(String location)
    {
        this.location = location;
    }

    public BigDecimal getPaidUntil()
    {
        return this.paidUntil;
    }

    public void setPaidUntil(BigDecimal paidUntil)
    {
        this.paidUntil = paidUntil;
    }

    public boolean isGrade()
    {
        return this.grade;
    }

    public void setGrade(boolean grade)
    {
        this.grade = grade;
    }

}
