package net.sf.l2j.loginserver.beans;

// Generated 11 déc. 2006 17:28:16 by Hibernate Tools 3.2.0.beta8

/**
 * ClanSubpledgesId generated by hbm2java
 */
public class ClanSubpledgesId implements java.io.Serializable
{

    // Fields    

    private int clanId;
    private int subPledgeId;

    // Constructors

    /** default constructor */
    public ClanSubpledgesId()
    {
    }

    /** full constructor */
    public ClanSubpledgesId(int clanId, int subPledgeId)
    {
        this.clanId = clanId;
        this.subPledgeId = subPledgeId;
    }

    // Property accessors
    public int getClanId()
    {
        return this.clanId;
    }

    public void setClanId(int clanId)
    {
        this.clanId = clanId;
    }

    public int getSubPledgeId()
    {
        return this.subPledgeId;
    }

    public void setSubPledgeId(int subPledgeId)
    {
        this.subPledgeId = subPledgeId;
    }

    public boolean equals(Object other)
    {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof ClanSubpledgesId)) return false;
        ClanSubpledgesId castOther = (ClanSubpledgesId) other;

        return (this.getClanId() == castOther.getClanId())
            && (this.getSubPledgeId() == castOther.getSubPledgeId());
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + this.getClanId();
        result = 37 * result + this.getSubPledgeId();
        return result;
    }

}
