package net.sf.l2j.loginserver.beans;

// Generated 7 déc. 2006 18:49:51 by Hibernate Tools 3.2.0.beta8

/**
 * Items generated by hbm2java
 */
public class Items implements java.io.Serializable
{

    // Fields    

    private int objectId;
    private Integer ownerId;
    private Integer itemId;
    private Integer count;
    private Integer enchantLevel;
    private String loc;
    private Integer locData;
    private Integer priceSell;
    private Integer priceBuy;
    private Integer timeOfUse;
    private Integer customType1;
    private Integer customType2;

    // Constructors

    /** default constructor */
    public Items()
    {
    }

    /** minimal constructor */
    public Items(int objectId)
    {
        this.objectId = objectId;
    }

    /** full constructor */
    public Items(int objectId, Integer ownerId, Integer itemId, Integer count, Integer enchantLevel,
                 String loc, Integer locData, Integer priceSell, Integer priceBuy, Integer timeOfUse,
                 Integer customType1, Integer customType2)
    {
        this.objectId = objectId;
        this.ownerId = ownerId;
        this.itemId = itemId;
        this.count = count;
        this.enchantLevel = enchantLevel;
        this.loc = loc;
        this.locData = locData;
        this.priceSell = priceSell;
        this.priceBuy = priceBuy;
        this.timeOfUse = timeOfUse;
        this.customType1 = customType1;
        this.customType2 = customType2;
    }

    // Property accessors
    public int getObjectId()
    {
        return this.objectId;
    }

    public void setObjectId(int objectId)
    {
        this.objectId = objectId;
    }

    public Integer getOwnerId()
    {
        return this.ownerId;
    }

    public void setOwnerId(Integer ownerId)
    {
        this.ownerId = ownerId;
    }

    public Integer getItemId()
    {
        return this.itemId;
    }

    public void setItemId(Integer itemId)
    {
        this.itemId = itemId;
    }

    public Integer getCount()
    {
        return this.count;
    }

    public void setCount(Integer count)
    {
        this.count = count;
    }

    public Integer getEnchantLevel()
    {
        return this.enchantLevel;
    }

    public void setEnchantLevel(Integer enchantLevel)
    {
        this.enchantLevel = enchantLevel;
    }

    public String getLoc()
    {
        return this.loc;
    }

    public void setLoc(String loc)
    {
        this.loc = loc;
    }

    public Integer getLocData()
    {
        return this.locData;
    }

    public void setLocData(Integer locData)
    {
        this.locData = locData;
    }

    public Integer getPriceSell()
    {
        return this.priceSell;
    }

    public void setPriceSell(Integer priceSell)
    {
        this.priceSell = priceSell;
    }

    public Integer getPriceBuy()
    {
        return this.priceBuy;
    }

    public void setPriceBuy(Integer priceBuy)
    {
        this.priceBuy = priceBuy;
    }

    public Integer getTimeOfUse()
    {
        return this.timeOfUse;
    }

    public void setTimeOfUse(Integer timeOfUse)
    {
        this.timeOfUse = timeOfUse;
    }

    public Integer getCustomType1()
    {
        return this.customType1;
    }

    public void setCustomType1(Integer customType1)
    {
        this.customType1 = customType1;
    }

    public Integer getCustomType2()
    {
        return this.customType2;
    }

    public void setCustomType2(Integer customType2)
    {
        this.customType2 = customType2;
    }

}
