package net.sf.l2j.loginserver.beans;

// Generated 11 déc. 2006 17:28:16 by Hibernate Tools 3.2.0.beta8

/**
 * MerchantLease generated by hbm2java
 */
public class MerchantLease implements java.io.Serializable
{

    // Fields    

    private MerchantLeaseId id;
    private Characters characters;
    private Integer bid;
    private String playerName;

    // Constructors

    /** default constructor */
    public MerchantLease()
    {
    }

    /** minimal constructor */
    public MerchantLease(MerchantLeaseId id, Characters characters)
    {
        this.id = id;
        this.characters = characters;
    }

    /** full constructor */
    public MerchantLease(MerchantLeaseId id, Characters characters, Integer bid, String playerName)
    {
        this.id = id;
        this.characters = characters;
        this.bid = bid;
        this.playerName = playerName;
    }

    // Property accessors
    public MerchantLeaseId getId()
    {
        return this.id;
    }

    public void setId(MerchantLeaseId id)
    {
        this.id = id;
    }

    public Characters getCharacters()
    {
        return this.characters;
    }

    public void setCharacters(Characters characters)
    {
        this.characters = characters;
    }

    public Integer getBid()
    {
        return this.bid;
    }

    public void setBid(Integer bid)
    {
        this.bid = bid;
    }

    public String getPlayerName()
    {
        return this.playerName;
    }

    public void setPlayerName(String playerName)
    {
        this.playerName = playerName;
    }

}
