package net.sf.l2j.loginserver.beans;

// Generated 7 déc. 2006 18:49:51 by Hibernate Tools 3.2.0.beta8

/**
 * MerchantLeaseId generated by hbm2java
 */
public class MerchantLeaseId implements java.io.Serializable
{

    // Fields    

    private int merchantId;
    private int playerId;
    private int type;

    // Constructors

    /** default constructor */
    public MerchantLeaseId()
    {
    }

    /** full constructor */
    public MerchantLeaseId(int merchantId, int playerId, int type)
    {
        this.merchantId = merchantId;
        this.playerId = playerId;
        this.type = type;
    }

    // Property accessors
    public int getMerchantId()
    {
        return this.merchantId;
    }

    public void setMerchantId(int merchantId)
    {
        this.merchantId = merchantId;
    }

    public int getPlayerId()
    {
        return this.playerId;
    }

    public void setPlayerId(int playerId)
    {
        this.playerId = playerId;
    }

    public int getType()
    {
        return this.type;
    }

    public void setType(int type)
    {
        this.type = type;
    }

    public boolean equals(Object other)
    {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof MerchantLeaseId)) return false;
        MerchantLeaseId castOther = (MerchantLeaseId) other;

        return (this.getMerchantId() == castOther.getMerchantId())
            && (this.getPlayerId() == castOther.getPlayerId())
            && (this.getType() == castOther.getType());
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + this.getMerchantId();
        result = 37 * result + this.getPlayerId();
        result = 37 * result + this.getType();
        return result;
    }

}
