CREATE TABLE IF NOT EXISTS `custom_teleport` (
  `Description` VARCHAR(75) DEFAULT NULL,
  `id` DECIMAL(11,0) NOT NULL DEFAULT 0,
  `loc_x` DECIMAL(9,0) DEFAULT NULL,
  `loc_y` DECIMAL(9,0) DEFAULT NULL,
  `loc_z` DECIMAL(9,0) DEFAULT NULL,
  `price` DECIMAL(6,0) DEFAULT NULL,
  `fornoble` INT(1) NOT NULL DEFAULT 0,
  `itemId` DECIMAL(11,0) NOT NULL DEFAULT '57',
  PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;
