package elayne;

/**
 * This interface defines all the pictures that the plug in requires.
 * @author polbat02
 */
public interface IImageKeys
{
	public static final String ABORT_SERVER_RESTART = "icons/control_play_blue.png";
	public static final String ACCOUNT_INFORMATION = "icons/etc_box_of_adventure_2_i00.png";
	public static final String ADD_BANNED_PLAYER = "icons/error_add.png";
	public static final String ANNOUNCE = "icons/comments.png";
	public static final String ARMOR_GROUP = "icons/armor.png";
	public static final String BAN_ACCOUNT = "icons/flag_orange.png";
	public static final String BAN_ALL_ACCOUNTS = "icons/flag_red.png";
	public static final String BAN_PLAYER = "icons/flag_yellow.png";
	public static final String BANNED = "icons/status_busy.png";
	public static final String BANNED_GROUP = "icons/status_busy.png";
	public static final String BANNED_PLAYER = "icons/status_busy.png";
	public static final String CASTLE = "icons/etc_ancient_crown_i02.png";
	public static final String CHANGE_NAME = "icons/textfield_rename.png";
	public static final String CHANGE_PASSWORD = "icons/textfield_key.png";
	public static final String CLAN_GROUP = "icons/etc_bloodpledge_point_i00.png";
	public static final String CLANHALL = "icons/clanhall.png";
	public static final String CLAN_MEMBERS_GROUP = "icons/action041.png";
	public static final String CLEAR_KARMA = "icons/pill_go.png";
	public static final String DARK_ELF_FEMALE = "icons/darkelf_female.gif";
	public static final String DARK_ELF_MALE = "icons/darkelf_male.gif";
	public static final String DATABASE_CONNECT = "icons/database_connect.png";
	public static final String DATABASE_CONNECTED = "icons/connect.png";
	public static final String DATABASE_DISCONNECTED = "icons/disconnect.png";
	public static final String DELETE = "icons/cross.png";
	public static final String DELETE_ITEM = "icons/cut_red.png";
	public static final String DELETE_NOBLE = "icons/award_star_delete.png";
	public static final String DELETE_SKILL = "icons/package_delete.png";
	public static final String DWARF_FEMALE = "icons/dwarf_female.gif";
	public static final String DWARF_MALE = "icons/dwarf_male.gif";
	public static final String ELF_FEMALE = "icons/elf_female.gif";
	public static final String ELF_MALE = "icons/elf_male.gif";
	public static final String EXIT = "icons/door_out.png";
	public static final String FEMALE_ONLINE = "icons/female.png";
	public static final String FOLDER = "icons/folder_user.png";
	public static final String FORTRESS = "icons/fortress.png";
	public static final String GENERAL = "icons/alt16.gif";
	public static final String GROUP = "icons/lock.png";
	public static final String HENNA_CON = "icons/conn.png";
	public static final String HENNA_DEX = "icons/dex.png";
	public static final String HENNA_INT = "icons/int.png";
	public static final String HENNA_MEN = "icons/men.png";
	public static final String HENNA_STR = "icons/str.png";
	public static final String HENNA_WIT = "icons/wit.png";
	public static final String HUMAN_FEMALE = "icons/human_female.gif";
	public static final String HUMAN_MALE = "icons/human_male.gif";
	public static final String INFORMATION = "icons/information.png";
	public static final String INVENTORY_GROUP = "icons/inventory.png";
	public static final String ITEM_GROUP = "icons/item.png";
	public static final String JAIL_PLAYER = "icons/lock_delete.png";
	public static final String KICK_PLAYER = "icons/key_go.png";
	public static final String KICK_PLAYER_FROM_CLAN = "icons/door_out.png";
	public static final String MAKE_NOBLE = "icons/award_star_add.png";
	public static final String MALE_ONLINE = "icons/male.png";
	public static final String NAME = "icons/book.png";
	public static final String OFFLINE = "icons/status_offline.png";
	public static final String ONLINE = "icons/status_online.png";
	public static final String ONLINE_GROUP = "icons/group.png";
	public static final String ORC_FEMALE = "icons/orc_female.gif";
	public static final String ORC_MALE = "icons/orc_male.gif";
	public static final String PIC_NOT_FOUND = "icons/skill4416_etc.png";
	public static final String REFRESH = "icons/arrow_refresh.png";
	public static final String SEARCH = "icons/zoom.png";
	public static final String SEND_GM_CHAT = "icons/comment_add.png";
	public static final String SEND_PRIVATE_MESSAGE = "icons/user_comment.png";
	public static final String SERVER_RESTART = "icons/control_repeat_blue.png";
	public static final String SERVER_SHUT_DOWN = "icons/control_stop_blue.png";
	public static final String SKILLS_GROUP = "icons/etc_flower_i02.png";
	public static final String SORT_BY_ACCESSLEVEL = "icons/award_star_bronze_3.png";
	public static final String SORT_BY_LEVEL = "icons/text_list_numbers.png";
	public static final String SORT_BY_NAME = "icons/text_padding_left.png";
	public static final String SORT_BY_SEX = "icons/text_letter_omega.png";
	public static final String STATS_GROUP = "icons/stats.png";
	public static final String SUBCLASS_GROUP = "icons/subs.png";
	public static final String TELEPORT = "icons/world_go.png";
	public static final String UN_BAN_ACCOUNT = "icons/flag_blue.png";
	public static final String UN_BAN_ALL_ACCOUNTS = "icons/flag_green.png";
	public static final String UN_BAN_PLAYER = "icons/flag_pink.png";
	public static final String UN_JAIL_PLAYER = "icons/lock_open.png";
	public static final String WEAPON_GROUP = "icons/weapon_angel_slayer_i00.png";
	public static final String WIPE_INVENTORY = "icons/basket_delete.png";
	public static final String WIPE_SKILLS = "icons/chart_pie_delete.png";
}
